{
 "title": "MTR monitoring Elastic",
 "description": "https://github.com/mirsafari/mtr-monitoring-elastic",
 "tags": [
  "mtr",
  "traceroute",
  "elasticsearch",
  "network"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "monitor_name",
    "label": "Endpoint",
    "query": "{\"find\": \"terms\", \"field\": \"monitor_name\", \"size\": 1000}\t"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "average RTT to endpoint (ms) top 10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:419",
       "fake": true,
       "field": "monitor_name",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:301",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:100",
       "field": "endpoint_ping_avg_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "mtr_report: \"fullpath\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Highest latency Top 10",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:419",
       "fake": true,
       "field": "monitor_name",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:301",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:100",
       "field": "endpoint_ping_avg_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "mtr_report: \"fullpath\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Highest loss Top 10",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:419",
       "fake": true,
       "field": "monitor_name",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:301",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:100",
       "field": "endpoint_pct_loss",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "mtr_report: \"fullpath\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Statistics for $monitor_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "monitor_name",
   "collapsed": true,
   "panels": [
    {
     "title": "avg RTT per hop (ms)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:419",
         "fake": true,
         "field": "hop_ip",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:301",
         "fake": true,
         "field": "@timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:100",
         "field": "hop_ping_avg_ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor_name: $monitor_name AND mtr_report: \"hop\" AND NOT hop_ip: \"???\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "average RTT to endpoint (ms)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:419",
         "fake": true,
         "field": "monitor_name",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:301",
         "fake": true,
         "field": "@timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:100",
         "field": "endpoint_ping_avg_ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor_name: $monitor_name AND mtr_report: \"fullpath\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg PINGLOSS per hop (pct)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:419",
         "fake": true,
         "field": "hop_ip",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:301",
         "fake": true,
         "field": "@timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:100",
         "field": "hop_pct_loss",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor_name: $monitor_name AND mtr_report: \"hop\" AND NOT hop_ip: \"???\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": " avg PINGLOSS to endpoint (pct)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:419",
         "fake": true,
         "field": "monitor_name",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:301",
         "fake": true,
         "field": "@timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:100",
         "field": "endpoint_pct_loss",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor_name: $monitor_name AND mtr_report: \"fullpath\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}